spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver