import Head from "next/head";
import { Inter } from "@next/font/google";
import SignIn from "./signIn";
import Nav from "../components/Nav";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Yesee World</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid h-screen w-screen place-content-center bg-slate-200">
        <div className="">환영합니다 ^_^</div>
      </main>
    </>
  );
}
